spring:
  datasource:
    url: jdbc:mysql://127.0.0.1\:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  #控制台输出彩色日志（工具必须支持ANSI）
  output:
    ansi:
      enabled: always
