spring:
  datasource:
    url: jdbc:mysql://10.129.255.53:3306/audit?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  session:
    store-type: redis
  redis:
    host: 10.129.255.53
    port: 6379
    password:
  http:
    multipart:
      max-file-size: 1000Mb
      max-request-size: 1000Mb


#数据库密码加密
#java -cp druid-1.1.5.jar com.alibaba.druid.filter.config.ConfigTools 你的密码
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIORC+/4odgX86yLco6jdWFzhke9Qfe/D78vrj3huI5ILula86opdj87v6vh+UZA9pih5HfhI0VjSfj4A10MjuUCAwEAAQ==
password: dfziRygqZEaKZPAHGaGDRV1JPboXqNS+zYxWihTcCeKO4msehDTkEv5mMnBVEpDKdQkekfcOJzWUG+i8qYJheQ==

ftp:
  host: 10.129.255.50
  port: 21
  username: ftpuser
  password: kVfW3h7vK9Q+yHqVcEr/J8TgrPCDwH/5RlcGsUYV9B66YK39VMgSJptwD8m86Sr2Igy9MXVaVkl37dhtPSmtEw==
oa:
  secretkey: caud9681

engine:
  url: http://10.129.255.52:8090/
  enginneering:
    settlementFlowId: a2716c0952ac98dc6348528c6b4a5eea
    finalSettlementFlowId: 75eed3694eb35cfa92f2537700b92375
    suspendflowId: c819636250ed2a62213e3a934b6904f3
    returnflowId: 814a6e6bff86f4b10dd93c5030a5a485
    finalSuspendflowId: d135d34fb93edc795ca99fd9dba617fa
    finalReturnflowId: abeabbdc5b491cf39885d7cef28f33e8