spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: ${password}
  #控制台输出彩色日志（工具必须支持ANSI）
  output:
    ansi:
      enabled: always
  http:
    multipart:
      max-file-size: 1000Mb
      max-request-size: 1000Mb

#数据库密码加密
#java -cp druid-1.1.5.jar com.alibaba.druid.filter.config.ConfigTools 你的密码
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJjPtWKq1CKbCIcNFCFGr2lKI/Jvp9GZ/+0YzG4skiAhRYtWFBr3q2AEeoP7EPIauh+NHzSM3o6G2yiF5kTTIx0CAwEAAQ==
password: BUA+TIEAt+7Jq+DjDhXNPwxB4JLOlO9XfnUfwH6IhEcvhtkCUU1ObjHryx55z+QYew2w2k4KyzgQvL/x75sHIg==
